### PR TITLE
Shape filters

### LINKED ISSUE #2: Shape filters
**Truncate** 

``` new Truncate($maxLengh)```

- Applied to an array [Collection, List]
- Removes items from end of array such that the array contains at most $maxLength items
- Returns unchanged if existing length is < $maxLength
- Construct should throw exception if $maxLength < 1

** Pluck **

``` new Pluck($from, ...$fieldNames)```

- Applied to an Keyed array [Fieldset]
- Fieldset must contain the key `$from`
- `$from` must be a Keyed array [Fieldset]
- Filter will copy the keys designated by `$fieldNames` from the source Fieldset `$from` into the destination Fieldset which this is applied to 
- No effect if `$from` doesnt' exist
- Non-existant `$fieldNames` are ignored

** Delete **

``` new Delete(...$fieldNames)```

- Applied to a Keyed array [Fieldset]
- Will delete the keys `$fieldNames` from it
- Non-existant `$fieldNames` are ignored

** Rename **

``` new Rename($old, $new)```

- Applied to a Keyed array [Fieldset]
- Will rename the key `$old` to `$new`
- Non-existant `$old` will return the fieldset unchanged

### PR DESCRIPTION
**Pull request by jrcharm**
fixes #2 

Shape filters implemented

Truncate filter truncates lists only, making sure they are equal or below maxLength

Delete filter deletes a key from arrays only

Rename filter renames a key on arrays only

Pluck filter works on arrays only and achieves same result as example provided

### CODE REVIEW

File: src/Filter/Shape/Pluck.php [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+            $message = new Message('Pluck filter requires arrays, %s given', [gettype($value)]);
+            return Result::invalid($value, new MessageSet(null, $message));
+        }
+
+        if (array_is_list($value)) {
+            $message = new Message('Pluck filter requires arrays with key-value pairs', []);
+            return Result::invalid($value, new MessageSet(null, $message));
+        }
+
+        $from = $value[$this->fieldSet] ?? null;
```
Comment (carnage) [inline src/Filter/Shape/Pluck.php:35]: I think PHPStan will (Eventually) be happier if this was an array instead of null as a default value. An empty array is also more semantically correct, as that's what the code below is expecting.

File: src/Filter/Shape/Rename.php [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+use Membrane\Result\MessageSet;
+use Membrane\Result\Result;
+
+class Rename implements Filter
+{
+    public function __construct(
+        private readonly string $old,
+        private readonly string $new
+    )
+    {
```
Comment (carnage) [inline src/Filter/Shape/Rename.php:18]: Wonder if its worth throwing an exception if $old === $new. In this instance the filter would behave as a delete filter, which is almost certainly a developer error

Comment (jrcharm) [reply src/Filter/Shape/Rename.php:19]: Rename: I've added a RuntimeException if `$old === $new`

Pluck: I've changed it to `$from = $value[$this->fieldSet] ?? [];` 
    This still passes all tests since an empty array is considered a list so `if (is_array($from) && !array_is_list($from))` will return false.
